export const clothesAction = {
  FETCH_CLOTHES_REQUEST: "FETCH_CLOTHES_REQUEST",
  FETCH_CLOTHES_SUCCESS: "FETCH_CLOTHES_SUCCESS",
  FETCH_CLOTHES_FAILURE: "FETCH_CLOTHES_FAILURE",
  ON_ITEM_SELECTED: "ON_ITEM_SELECTED",

  PRODUCT_ADDED_TO_BAG: "PRODUCT_ADDED_TO_BAG",
  PRODUCT_REMOVED_FROM_BAG: "PRODUCT_REMOVED_FROM_BAG",
  PRODUCT_ALL_REMOVED_FROM_BAG: "PRODUCT_ALL_REMOVED_FROM_BAG",
  SEARCH_CLOTHES: "SEARCH_CLOTHES",
  ON_FILTER_CLOTHES: "ON_FILTER_CLOTHES",

  ON_FILTER_SIZE: "ON_FILTER_SIZE",
  ON_FILTER_PRICE: "ON_FILTER_PRICE",
  ON_FILTER_FABRIC: "ON_FILTER_FABRIC",
};
